/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiThaiExamRoomsRouteImport } from './routes/api/thai-exam-rooms'
import { Route as ProtectedSelectExamsRouteImport } from './routes/_protected/select-exams'
import { Route as ProtectedScheduleRouteImport } from './routes/_protected/schedule'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThaiExamRoomsRoute = ApiThaiExamRoomsRouteImport.update({
  id: '/api/thai-exam-rooms',
  path: '/api/thai-exam-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSelectExamsRoute = ProtectedSelectExamsRouteImport.update({
  id: '/select-exams',
  path: '/select-exams',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedScheduleRoute = ProtectedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schedule': typeof ProtectedScheduleRoute
  '/select-exams': typeof ProtectedSelectExamsRoute
  '/api/thai-exam-rooms': typeof ApiThaiExamRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schedule': typeof ProtectedScheduleRoute
  '/select-exams': typeof ProtectedSelectExamsRoute
  '/api/thai-exam-rooms': typeof ApiThaiExamRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/schedule': typeof ProtectedScheduleRoute
  '/_protected/select-exams': typeof ProtectedSelectExamsRoute
  '/api/thai-exam-rooms': typeof ApiThaiExamRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schedule' | '/select-exams' | '/api/thai-exam-rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schedule' | '/select-exams' | '/api/thai-exam-rooms'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/schedule'
    | '/_protected/select-exams'
    | '/api/thai-exam-rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiThaiExamRoomsRoute: typeof ApiThaiExamRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/thai-exam-rooms': {
      id: '/api/thai-exam-rooms'
      path: '/api/thai-exam-rooms'
      fullPath: '/api/thai-exam-rooms'
      preLoaderRoute: typeof ApiThaiExamRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/select-exams': {
      id: '/_protected/select-exams'
      path: '/select-exams'
      fullPath: '/select-exams'
      preLoaderRoute: typeof ProtectedSelectExamsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/schedule': {
      id: '/_protected/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ProtectedScheduleRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedScheduleRoute: typeof ProtectedScheduleRoute
  ProtectedSelectExamsRoute: typeof ProtectedSelectExamsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedScheduleRoute: ProtectedScheduleRoute,
  ProtectedSelectExamsRoute: ProtectedSelectExamsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiThaiExamRoomsRoute: ApiThaiExamRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
